package com.allan.springbootmybatis.entity;

import lombok.Data;

/**
 * Database Table Remarks:
 *   全国火车高铁站表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table T_STATION_INFO
 */
@Data
public class StationInfo {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.ID
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String id;

    /**
     * Database Column Remarks:
     *   车站名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STATION_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String stationName;

    /**
     * Database Column Remarks:
     *   车站拼音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STATION_NAME_EN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String stationNameEn;

    /**
     * Database Column Remarks:
     *   拼音简写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.SHORT_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String shortName;

    /**
     * Database Column Remarks:
     *   车站三字码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STATION_CODE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String stationCode;

    /**
     * Database Column Remarks:
     *   拼音首字母
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.NAME_SORT
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String nameSort;

    /**
     * Database Column Remarks:
     *   所在城市/地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.CITY_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String cityName;

    private String cityCode;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STA_SEQUENCE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private Integer staSequence;

    /**
     * Database Column Remarks:
     *   拼音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.PIN_YIN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String pinYin;

}