package com.allan.springbootmybatis.entity;

/**
 * Database Table Remarks:
 *   全国火车高铁站表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table T_STATION_INFO
 */
public class StationInfo {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.ID
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String id;

    /**
     * Database Column Remarks:
     *   车站名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STATION_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String stationName;

    /**
     * Database Column Remarks:
     *   车站拼音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STATION_NAME_EN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String stationNameEn;

    /**
     * Database Column Remarks:
     *   拼音简写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.SHORT_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String shortName;

    /**
     * Database Column Remarks:
     *   车站三字码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STATION_CODE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String stationCode;

    /**
     * Database Column Remarks:
     *   拼音首字母
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.NAME_SORT
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String nameSort;

    /**
     * Database Column Remarks:
     *   所在城市/地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.CITY_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String cityName;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.STA_SEQUENCE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private Integer staSequence;

    /**
     * Database Column Remarks:
     *   拼音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STATION_INFO.PIN_YIN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    private String pinYin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.ID
     *
     * @return the value of T_STATION_INFO.ID
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.ID
     *
     * @param id the value for T_STATION_INFO.ID
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.STATION_NAME
     *
     * @return the value of T_STATION_INFO.STATION_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.STATION_NAME
     *
     * @param stationName the value for T_STATION_INFO.STATION_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.STATION_NAME_EN
     *
     * @return the value of T_STATION_INFO.STATION_NAME_EN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getStationNameEn() {
        return stationNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.STATION_NAME_EN
     *
     * @param stationNameEn the value for T_STATION_INFO.STATION_NAME_EN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setStationNameEn(String stationNameEn) {
        this.stationNameEn = stationNameEn == null ? null : stationNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.SHORT_NAME
     *
     * @return the value of T_STATION_INFO.SHORT_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.SHORT_NAME
     *
     * @param shortName the value for T_STATION_INFO.SHORT_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.STATION_CODE
     *
     * @return the value of T_STATION_INFO.STATION_CODE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.STATION_CODE
     *
     * @param stationCode the value for T_STATION_INFO.STATION_CODE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.NAME_SORT
     *
     * @return the value of T_STATION_INFO.NAME_SORT
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getNameSort() {
        return nameSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.NAME_SORT
     *
     * @param nameSort the value for T_STATION_INFO.NAME_SORT
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setNameSort(String nameSort) {
        this.nameSort = nameSort == null ? null : nameSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.CITY_NAME
     *
     * @return the value of T_STATION_INFO.CITY_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.CITY_NAME
     *
     * @param cityName the value for T_STATION_INFO.CITY_NAME
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.STA_SEQUENCE
     *
     * @return the value of T_STATION_INFO.STA_SEQUENCE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public Integer getStaSequence() {
        return staSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.STA_SEQUENCE
     *
     * @param staSequence the value for T_STATION_INFO.STA_SEQUENCE
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setStaSequence(Integer staSequence) {
        this.staSequence = staSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STATION_INFO.PIN_YIN
     *
     * @return the value of T_STATION_INFO.PIN_YIN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public String getPinYin() {
        return pinYin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STATION_INFO.PIN_YIN
     *
     * @param pinYin the value for T_STATION_INFO.PIN_YIN
     *
     * @mbg.generated Sat Jan 09 20:00:51 CST 2021
     */
    public void setPinYin(String pinYin) {
        this.pinYin = pinYin == null ? null : pinYin.trim();
    }
}