string:
#   使用redis 作为缓存
    redis:
#     # Redis服务器地址
      host: 127.0.0.1
#      # Redis服务器连接密码（默认为空）
      password:
#      # Redis服务器端口
      port: 6379
#    # 连接超时时间（毫秒）
      timeout: 0
#      #Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
      database: 0
      pool:
#        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#        # 连接池中的最大空闲连接
        max-idle: 8
#         # 连接池中的最小空闲连接
        min-idle: 0











